port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
  - name: 01
    type: socks5
    server: 106.75.152.119
    port: "1000"
    username: 8ccd48de-f5ac3e4f-b0bfff
    password: wifi-tr--adiyaman+province-
    udp: true
proxy-providers:
          机场:
            type: http
            url: https://villa.parkson-market.org/api/v1/trails/bolster?token=e54c7d16879b7901fa290f6e7b238d4d
            interval: 86400
            path: ./proxy_provider/jc.yaml
            udp: false
            health-check:
              enable: true
              interval: 600
              url: http://www.gstatic.com/generate_204
proxy-groups:
  - name: 主线路
    proxies:
      - DIRECT
      - 谷歌华为
    use:
      - 机场
    type: select
    disable-udp: true
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  - name: 谷歌华为
    proxies:
      - 01
    type: select
    disable-udp: false
    health-check:
      enable: false
      interval: 600
      url: http://www.gstatic.com/generate_204
rules:
  - DOMAIN,play.googleapis.com,谷歌华为
  - DOMAIN,myaccount.google.com,谷歌华为
  - DOMAIN-KEYWORD,accounts.google.com,谷歌华为
  - DOMAIN,play-fe.googleapis.com,谷歌华为
  - DOMAIN,sspanel.net,谷歌华为
  - DOMAIN,payments-pa.googleapis.com,谷歌华为
  - DOMAIN-KEYWORD,orders-dra.iap.cloud.huawei,谷歌华为
  - DOMAIN-SUFFIX,acs.cupdapp.cn,谷歌华为
  - DOMAIN-KEYWORD,iap-pay-dra.cloud.huawei,谷歌华为
  - MATCH,主线路